# Generated by Django 4.1.3 on 2022-11-20 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="photos/%Y/%m/%d/")),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Site Photos",
                "db_table": "Photos",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(
                        upload_to="videos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "avi",
                                    "mov",
                                    "wmv",
                                    "flv",
                                    "mkv",
                                    "webm",
                                    "3gp",
                                    "3g2",
                                    "m4v",
                                    "mpeg",
                                    "mpg",
                                    "mpe",
                                    "mpv",
                                    "m2v",
                                    "m4v",
                                    "svi",
                                    "3gp",
                                    "3g2",
                                    "mxf",
                                    "roq",
                                    "nsv",
                                    "f4v",
                                    "f4p",
                                    "f4a",
                                    "f4b",
                                ]
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Videos",
                "db_table": "Videos",
            },
        ),
    ]
